# Generated by Django 6.0.1 on 2026-02-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_userprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills extracted from CV', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills required for this job', null=True),
        ),
    ]
