# Generated by Django 6.0.1 on 2026-02-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma-separated languages', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='Comma-separated soft skills', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated technical skills', null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobs.cv')),
            ],
        ),
    ]
